### ISSUE TITLE
Proxy issue [probably]

### ISSUE THREAD

**Issue by themanyfaceddemon** [Strvm/meta-ai-api#11]
Perhaps I made a mistake somewhere when creating a proxy. The following happens:
With this code:
```python
from meta_ai_api import MetaAI
import requests

proxy_ip = '157.25.92.74'
proxy_port = 3128

proxies = {
    'http': f'http://{proxy_ip}:{proxy_port}'
}

try:
    ai = MetaAI(proxy=proxies)
    response = ai.prompt(message="How to find out which mushrooms are edible?")
except ConnectionError as ce:
    print(f"CE: {ce}")
except TimeoutError as te:
    print(f"TE: {te}")
except Exception as err:
    print(f"ERR: {err}")
```
The program displays my current IP. 
Still, there was no need to try to write the connection proxy code myself. Or I don't understand something

**Comment by Strvm** [comment]
I think it might be due to the fact that we are doing HTTP(S) requests, so the session doesn't use http proxies

**Comment by themanyfaceddemon** [comment]
I'll take a look later. Probably in 30 hours.

**Comment by themanyfaceddemon** [comment]
In short, maybe I can't connect to the proxy simply because of the provider, or some other reason. I'll close issues. If I find a solution, I'll post it here

**Comment by themanyfaceddemon** [comment]
I found a solution to the problem
https://www.reddit.com/r/VPN/comments/1c7xhrm/how_to_access_meta_ai_with_a_vpn/?rdt=46595

**Comment by themanyfaceddemon** [comment]
![image](https://github.com/Strvm/meta-ai-api/assets/154847721/312f4a01-4024-4060-a22a-3bfb1b87e5ec)
The bottom line is to use proxies that come from the USA. Now I’ll try both protocols and see what works and what doesn’t.
