### ISSUE TITLE
[Q] Custom system prompt?

### ISSUE THREAD

**Issue by elliotwellick** [Strvm/meta-ai-api#12]
Hi,

Is there a way to use custom system prompt like : "You're an helpful assistant built by ..."

Thanks!

**Comment by klakho0400** [comment]
Hey, @Strvm any updates on this? as whenever I ask who are you it always says Meta AI.

**Comment by Strvm** [comment]
Hey, unfortunately this isn't available directly inside https://meta.ai/ (and not available in the backend API it uses). The only way would be to append to the start of your prompt your system message a
