### ISSUE TITLE
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 1/3.

### ISSUE THREAD

**Issue by themacmarketer** [Strvm/meta-ai-api#16]
I'm getting this response:

WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 1/3.
Exception: Unable to obtain a valid response from Meta AI. Try again later.

Any suggestions to address this would be much appreciated!  Thanks.

**Comment by RexsyBima** [comment]
But then i got error i described here, yesterday was fine keep in mind

https://github.com/Strvm/meta-ai-api/issues/17

**Comment by EddSJ** [comment]
I'm having the same error even though I'm using an Oregon VPN, and just to test that it isn't my implementation, I ran a file only with the necessary code to get a response:
`from meta_ai_api import MetaAI

ai = MetaAI()
response = ai.prompt(message="Whats the weather in San Francisco today? And what is the date?")
print(response)`

Error:

WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 1/3.
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 2/3.
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 3/3.
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 4/3.

**Comment by Gusklin** [comment]
I had the same problem, I just used my facebook login, MetaAI(fb_email="your_fb_email", fb_password="your_fb_password"), and it worked.

**Comment by EddSJ** [comment]
> I had the same problem, I just used my facebook login, MetaAI(fb_email="your_fb_email", fb_password="your_fb_password"), and it worked.

Just with the email and password?, cause I try the same but im getting a new error 

`line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='xs', domain=None, path=None"`

**Comment by Gusklin** [comment]
> > I had the same problem, I just used my facebook login, MetaAI(fb_email="your_fb_email", fb_password="your_fb_password"), and it worked.
> 
> Just with the email and password?, cause I try the same but im getting a new error
> 
> `line 413, in _find_no_duplicates raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}") KeyError: "name='xs', domain=None, path=None"`

I am not getting this error, but I am getting a new one.

**Comment by Gusklin** [comment]
> > I had the same problem, I just used my facebook login, MetaAI(fb_email="your_fb_email", fb_password="your_fb_password"), and it worked.
> 
> Just with the email and password?, cause I try the same but im getting a new error
> 
> `line 413, in _find_no_duplicates raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}") KeyError: "name='xs', domain=None, path=None"`

I tried a VPN in another location on the US and got this error, try using protonVPN on US-FREE#519044

**Comment by RexsyBima** [comment]
> > > I had the same problem, I just used my facebook login, MetaAI(fb_email="your_fb_email", fb_password="your_fb_password"), and it worked.
> > 
> > 
> > Just with the email and password?, cause I try the same but im getting a new error
> > `line 413, in _find_no_duplicates raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}") KeyError: "name='xs', domain=None, path=None"`
> 
> I tried a VPN in another location on the US and got this error, try using protonVPN on US-FREE#519044

So.if u use protonVPN, its working on ur end? Because i got the same error but im using windscribe Vpn

**Comment by Gusklin** [comment]
> > > > I had the same problem, I just used my facebook login, MetaAI(fb_email="your_fb_email", fb_password="your_fb_password"), and it worked.
> > > 
> > > 
> > > Just with the email and password?, cause I try the same but im getting a new error
> > > `line 413, in _find_no_duplicates raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}") KeyError: "name='xs', domain=None, path=None"`
> > 
> > 
> > I tried a VPN in another location on the US and got this error, try using protonVPN on US-FREE#519044
> 
> So.if u use protonVPN, its working on ur end? Because i got the same error but im using windscribe Vpn

That specific server is working, but you have to accept the login on facebook, he will sent you a notification.

**Comment by RexsyBima** [comment]
i keep getting this error 

meta_ai_api.exceptions.FacebookInvalidCredentialsException: Was not able to login to Facebook. Please check your credentials. You may also have been rate limited. Try to connect to Facebook manually.

im using nordvpn now

**Comment by Gusklin** [comment]
> i keep getting this error
> 
> meta_ai_api.exceptions.FacebookInvalidCredentialsException: Was not able to login to Facebook. Please check your credentials. You may also have been rate limited. Try to connect to Facebook manually.
> 
> im using nordvpn now

Did you receive a notification on facebook? I had to accept first, the first time worked like a charm, but a few days later I tried again and had the same error that you have, I solved it by disconnecting from the VPN server to another server, then came back to the original server, #519044, try it on nordvpn

**Comment by RexsyBima** [comment]
> > i keep getting this error
> > meta_ai_api.exceptions.FacebookInvalidCredentialsException: Was not able to login to Facebook. Please check your credentials. You may also have been rate limited. Try to connect to Facebook manually.
> > im using nordvpn now
> 
> Did you receive a notification on facebook? I had to accept first, the first time worked like a charm, but a few days later I tried again and had the same error that you have, I solved it by disconnecting from the VPN server to another server, then came back to the original server, #519044 on protonVPN, try it on nordvpn

What countries vpn are u using?

**Comment by Gusklin** [comment]
> > > i keep getting this error
> > > meta_ai_api.exceptions.FacebookInvalidCredentialsException: Was not able to login to Facebook. Please check your credentials. You may also have been rate limited. Try to connect to Facebook manually.
> > > im using nordvpn now
> > 
> > 
> > Did you receive a notification on facebook? I had to accept first, the first time worked like a charm, but a few days later I tried again and had the same error that you have, I solved it by disconnecting from the VPN server to another server, then came back to the original server, #519044 on protonVPN, try it on nordvpn
> 
> What countries vpn are u using?

US

**Comment by RexsyBima** [comment]
> Meta Ai is available in singapore, did you get this error: KeyError: "name='xs', domain=None, path=None" when you tried without vpn?

what i meant was im connecting into singapore vpn, and yes i got taht error but with windscribe

https://github.com/Strvm/meta-ai-api/issues/17 check this

**Comment by RexsyBima** [comment]
> > > Meta Ai is available in singapore, did you get this error: KeyError: "name='xs', domain=None, path=None" when you tried without vpn?
> > 
> > 
> > what i meant was im connecting into singapore vpn, and yes i got that error but with windscribe
> > #17 check this
> 
> I got that error in another server while using VPN on USA, if there is more servers available in singapore, try change it and see if it works

Still the same to me,, im confused and don't know what to do
