### ISSUE TITLE
   raise FacebookRegionBlocked( meta_ai_api.exceptions.FacebookRegionBlocked: Unable to receive a valid response from Meta AI. This is likely due to your region being blocked. Try manually accessing https://www.meta.ai/ to confirm.

### ISSUE THREAD

**Issue by MominIqbal-1234** [Strvm/meta-ai-api#19]
i run meta-ai-api in codespace return this error

**Comment by Strvm** [comment]
Try running code locally. The IP of your code space might be flagged on Meta's side

**Comment by MominIqbal-1234** [comment]
thanks so much
i try in my local system but what if i host some time so then how i add proxy
