### ISSUE TITLE
Reusable sessions

### ISSUE THREAD

**Issue by ideas2bytes** [Strvm/meta-ai-api#22]
Hey Creator, I appreciate your work for Meta AI API. But, it would be nice, if you include reusable sessions. Like, If I start chatting with the AI, the next prompt should continue with the same conversation. The context should be preserved.

**Comment by Strvm** [comment]
Hi, this has now been implemented: #25 

Closing this now, thank you !

**Comment by aniruddhkrishnan** [comment]
> Hi, this has now been implemented: #25
> 
> Closing this now, thank you !

Thank you for this. I am very happy. I was waiting for this update for a long time. I am from India, and I study in 10th grade.
