### ISSUE TITLE
Exception: Unable to obtain a valid response from Meta AI. Try again later.

### ISSUE THREAD

**Issue by Dawgmastah** [Strvm/meta-ai-api#26]
It seems that facebook login may now be mandatory?
Im getting this error even in the example code.

**Comment by Dawgmastah** [comment]
Never mind, it seems it is related to VPN usage.

**Comment by Dawgmastah** [comment]
Actually it seems only SOME countries allow for inference without login.

**Comment by Strvm** [comment]
Try accessing https://www.meta.ai/ with your connection. Usually most times the website will require to log into a Meta account if it detects you are using a VPN. Also I believe European countries can't access it.

**Comment by Strvm** [comment]
As an example:

With NordVPN on (USA):
<img width="711" alt="Screenshot 2024-07-27 at 16 11 34" src="https://github.com/user-attachments/assets/28b04c65-9dd6-4f7b-9486-89506bb58f4a">

Without any VPN (USA Connection):
<img width="713" alt="Screenshot 2024-07-27 at 16 11 49" src="https://github.com/user-attachments/assets/e9ca9e26-6687-46e3-aee2-41e65c275a01">

**Comment by AnxiousAnt** [comment]
I am able to access [https://www.meta.ai/](https://www.meta.ai/) without needing to login, but i still get the same error:
`Exception: Unable to obtain a valid response from Meta AI. Try again later.`

**Comment by omkarxpatel** [comment]
@Strvm 

I currently have tested creating a MetaAI() session in both France and India. In france, neither the link or the api works. In India, the link works but the api does not. I get the error: `Exception: Unable to obtain a valid response from Meta AI. Try again later.` for both.

Therefore, I have attempted to connect to a US proxy via the MetaAI argument
```py
meta_client = MetaAI(proxy={
    'http': 'http://...',
    'https': 'http://...'
})
```
This does not work either.

**Comment by Strvm** [comment]
> @Strvm
> 
> I currently have tested creating a MetaAI() session in both France and India. In france, neither the link or the api works. In India, the link works but the api does not. I get the error: `Exception: Unable to obtain a valid response from Meta AI. Try again later.` for both.
> 
> Therefore, I have attempted to connect to a US proxy via the MetaAI argument
> 
> ```python
> meta_client = MetaAI(proxy={
>     'http': 'http://...',
>     'https': 'http://...'
> })
> ```
> 
> This does not work either.

Hi like I said above, France being in the European Union, https://meta.ai is not available there.

**Comment by omkarxpatel** [comment]
> > @Strvm
> > I currently have tested creating a MetaAI() session in both France and India. In france, neither the link or the api works. In India, the link works but the api does not. I get the error: `Exception: Unable to obtain a valid response from Meta AI. Try again later.` for both.
> > Therefore, I have attempted to connect to a US proxy via the MetaAI argument
> > ```python
> > meta_client = MetaAI(proxy={
> >     'http': 'http://...',
> >     'https': 'http://...'
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This does not work either.
> 
> Hi like I said above, France being in the European Union, https://meta.ai is not available there.

Right, what about India? the link works but the api does not. also, the proxy does not seem to work even tho it connects fine.

**Comment by Strvm** [comment]
> > > @Strvm
> > > I currently have tested creating a MetaAI() session in both France and India. In france, neither the link or the api works. In India, the link works but the api does not. I get the error: `Exception: Unable to obtain a valid response from Meta AI. Try again later.` for both.
> > > Therefore, I have attempted to connect to a US proxy via the MetaAI argument
> > > ```python
> > > meta_client = MetaAI(proxy={
> > >     'http': 'http://...',
> > >     'https': 'http://...'
> > > })
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This does not work either.
> > 
> > 
> > Hi like I said above, France being in the European Union, https://meta.ai is not available there.
> 
> Right, what about India? the link works but the api does not. also, the proxy does not seem to work even tho it connects fine.

How are you connecting with India, via VPN/Proxy? If thats the case, https://meta.ai/ might be flagging it as a VPN/Proxy.

**Comment by omkarxpatel** [comment]
> > > > @Strvm
> > > > I currently have tested creating a MetaAI() session in both France and India. In france, neither the link or the api works. In India, the link works but the api does not. I get the error: `Exception: Unable to obtain a valid response from Meta AI. Try again later.` for both.
> > > > Therefore, I have attempted to connect to a US proxy via the MetaAI argument
> > > > ```python
> > > > meta_client = MetaAI(proxy={
> > > >     'http': 'http://...',
> > > >     'https': 'http://...'
> > > > })
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > This does not work either.
> > > 
> > > 
> > > Hi like I said above, France being in the European Union, https://meta.ai is not available there.
> > 
> > 
> > Right, what about India? the link works but the api does not. also, the proxy does not seem to work even tho it connects fine.
> 
> How are you connecting with India, via VPN/Proxy? If thats the case, https://meta.ai/ might be flagging it as a VPN/Proxy.

The server itself is based in india

**Comment by Strvm** [comment]
> > > > > @Strvm
> > > > > I currently have tested creating a MetaAI() session in both France and India. In france, neither the link or the api works. In India, the link works but the api does not. I get the error: `Exception: Unable to obtain a valid response from Meta AI. Try again later.` for both.
> > > > > Therefore, I have attempted to connect to a US proxy via the MetaAI argument
> > > > > ```python
> > > > > meta_client = MetaAI(proxy={
> > > > >     'http': 'http://...',
> > > > >     'https': 'http://...'
> > > > > })
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > This does not work either.
> > > > 
> > > > 
> > > > Hi like I said above, France being in the European Union, https://meta.ai is not available there.
> > > 
> > > 
> > > Right, what about India? the link works but the api does not. also, the proxy does not seem to work even tho it connects fine.
> > 
> > 
> > How are you connecting with India, via VPN/Proxy? If thats the case, https://meta.ai/ might be flagging it as a VPN/Proxy.
> 
> The server itself is based in india

When connecting through india to https://meta.ai/, are you able to prompt the AI without logging into an account?

**Comment by omkarxpatel** [comment]
> > > > > > @Strvm
> > > > > > I currently have tested creating a MetaAI() session in both France and India. In france, neither the link or the api works. In India, the link works but the api does not. I get the error: `Exception: Unable to obtain a valid response from Meta AI. Try again later.` for both.
> > > > > > Therefore, I have attempted to connect to a US proxy via the MetaAI argument
> > > > > > ```python
> > > > > > meta_client = MetaAI(proxy={
> > > > > >     'http': 'http://...',
> > > > > >     'https': 'http://...'
> > > > > > })
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > This does not work either.
> > > > > 
> > > > > 
> > > > > Hi like I said above, France being in the European Union, https://meta.ai is not available there.
> > > > 
> > > > 
> > > > Right, what about India? the link works but the api does not. also, the proxy does not seem to work even tho it connects fine.
> > > 
> > > 
> > > How are you connecting with India, via VPN/Proxy? If thats the case, https://meta.ai/ might be flagging it as a VPN/Proxy.
> > 
> > 
> > The server itself is based in india
> 
> When connecting through india to https://meta.ai/, are you able to prompt the AI without logging into an account?

![image](https://github.com/user-attachments/assets/ca02c488-2ca0-4fbb-8249-c55ee41f7b7d)
This is what i see. able to prompt but after that i need to select age and then finish. maybe this is where the api is struggling?

**Comment by klakho0400** [comment]
Hi @Strvm I developed the Meta AI in a google cloud function but when it tries to call Meta AI it gives an error  Was unable to obtain a valid response from Meta AI. Retrying... Attempt 1/3. Can I fix this anyway?
