### ISSUE TITLE
Exception: Unable to obtain a valid response from Meta AI. Try again later.

### ISSUE THREAD

**Issue by ExyXyz** [Strvm/meta-ai-api#29]
so before it was working perfectly 
but suddenly it say that like can't be accesed 
im using digital ocean droplet - singapore
idk why that happen 
is my droplet is blocked by meta?

**Comment by Strvm** [comment]
Yes, having a datacenter IP is probably getting you blocked. 

Either host it somewhere else, or use proxies that aren't flagged by Meta

**Comment by ExyXyz** [comment]
awhh thank you tho
