### ISSUE TITLE
image generation not working ???

### ISSUE THREAD

**Issue by paisekamao** [Strvm/meta-ai-api#35]
(venv) E:\PROJECTS\meta>python api.py
Traceback (most recent call last):
  File "E:\PROJECTS\meta\api.py", line 2, in <module>
    ai = MetaAI(fb_email="*********", fb_password="***********")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PROJECTS\meta\venv\Lib\site-packages\meta_ai_api\main.py", line 50, in __init__
    self.cookies = self.get_cookies()
                   ^^^^^^^^^^^^^^^^^^
  File "E:\PROJECTS\meta\venv\Lib\site-packages\meta_ai_api\main.py", line 335, in get_cookies
    fb_session = get_fb_session(self.fb_email, self.fb_password)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\PROJECTS\meta\venv\Lib\site-packages\meta_ai_api\utils.py", line 107, in get_fb_session
    li = soup.find("input", {"name": "li"})["value"]
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

(venv) E:\PROJECTS\meta>

**Comment by Strvm** [comment]
Hi you need to be authenticated with FB to generate images.

**Comment by smandelli** [comment]
Hi @Strvm, I'm having the same issue... I've inserted my FB authentication details but I get the same error

**Comment by jackmvision** [comment]
same here. I've inserted my FB authentication details but I get the same error.

**Comment by Strvm** [comment]
FB Updated the login page I was using to check credentials. The new one has a lot more security on top of it, so currently can't log into FB

**Comment by jackmvision** [comment]
@Strvm Thanks for checking! Do you think you will release a fix soon?
