### ISSUE TITLE
How to avoid getting blocked by Meta?

### ISSUE THREAD

**Issue by tqdo** [Strvm/meta-ai-api#36]
First thanks for the great repo. Basically the title, how do I avoid getting blocked by Meta if I send many requests? Do you support any proxy services so that not all requests come from my IP

**Comment by Strvm** [comment]
Hi the API supports proxies:

```python
from meta_ai_api import MetaAI

proxy = {
    'http': 'http://proxy_address:port',
    'https': 'https://proxy_address:port'
}

ai = MetaAI(proxy=proxy)
response = ai.prompt(message="How to find out which mushrooms are edible?")
print(response)
```

Note that Meta might already be blocking some proxies (especially Datacenter IPs)
