### ISSUE TITLE
Markdown format is not returned

### ISSUE THREAD

**Issue by tqdo** [Strvm/meta-ai-api#40]
I notice that when streaming=True, initially the markdown is accurate but after a while the markdown syntaxes just disappeared. Is it a bug?

![Screenshot 2024-10-07 at 7 33 38 AM](https://github.com/user-attachments/assets/111cf062-17a7-421b-89ed-588cacdb0f1b)

**Comment by Strvm** [comment]
Hi, I just return what FB returns. Might need to do extra formatting on the output
