### ISSUE TITLE
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 1/3

### ISSUE THREAD

**Issue by harikrish432** [Strvm/meta-ai-api#41]
I have hosted the application on ec2 instance from Mumbai region. The application working fine in my local system but getting failed when deployed in AWS cloud platform.

**Comment by Jacob1802** [comment]
I was able to fix this by just creating a new instance. I assume this has to do with the context window, so if you login it might increase the size but I haven't tested it
