### ISSUE TITLE
Error in Accesing tokens

### ISSUE THREAD

**Issue by Sm7-git** [Strvm/meta-ai-api#53]
Traceback (most recent call last):
  File "D:/CyberEthics/Codiing/Meta_ccheck.py", line 4, in <module>
    response = ai.prompt(message="Whats the weather in San Francisco today? And what is the date?")
  File "D:\CyberEthics\Codiing\Lib\site-packages\tmeta_ai_api\main.py", line 126, in prompt
    self.access_token = self.get_access_token()
  File "D:\CyberEthics\Codiing\Lib\site-packages\tmeta_ai_api\main.py", line 93, in get_access_token
    access_token = auth_json["data"]["xab_abra_accept_terms_of_service"][
KeyError: 'data'

please i request the developer to take this issue seriously as my most of projerct is dependent on this

**Comment by Strvm** [comment]
Hi @Sm7-git , can you provide more info on where you are running your code? Any proxies? Are you trying to log into FB?

I tried locally and it works fine for me:

```python
    meta = MetaAI()
    resp = meta.prompt("What was the Warriors score last game?", stream=False)
    print(resp)
```

```
{'message': "The Warriors' last game was against the Houston Rockets on December 11, 2024, and they lost 90-91 ¹. However, I also found information on a more recent game against the Dallas Mavericks on December 15, 2024, where the Warriors scored 133 points but lost 133-143 ² ³.\n", 'sources': [{'link': 'https://sportradar.com/', 'title': 'Sport API'}, {'link': 'https://www.cbssports.com/nba/teams/GS/golden-state-warriors/', 'title': 'Golden State Warriors News, Scores, Status, Schedule - NBA'}, {'link': 'https://www.statmuse.com/nba/ask/warriors-stats-last-5-games', 'title': 'Warriors Stats Last 5 Games | StatMuse'}], 'media': []}

```

**Comment by Sm7-git** [comment]
Hey brother,
very much thankyou from my side now its working i don't know why from two days it was not working, i was in trouble as one of my project was totally dependent on it.

Thankyou very much.

**Comment by Sm7-git** [comment]
**Hey once again it stoppped working fix it permanently bro, my proxies and systems are alright i have checked in multiple systems.
I think this error is because the change in this format i think so see the image below this line is causing error i think there is change in its structure,**
![image](https://github.com/user-attachments/assets/e318212b-4f7d-4c5f-a77d-10ea0158ec5b)


Hey I have seen the structure, I meant i hyave tried to decode the structure and this was the format of main.MetaAI().get_access_token()
**{'errors': [{'message': 'A server error rate_limit_exceeded occured. Check server logs for details.', 'severity': 'CRITICAL', 'mids': ['991b9e8c3a46bf01eecdc2c98c663cbd'], 'code': 1348007, 'api_error_code': None, 'summary': 'ಲಾಗ್\u200cಇನ್ ಆಗಿರುವುದಿಲ್ಲ', 'description': {'__html': 'ಈ ಪುಟವನ್ನು ನೋಡಲು ಲಾಗಿನ ಮಾಡಿ.'}, 'description_raw': {'__html': 'ಈ ಪುಟವನ್ನು ನೋಡಲು ಲಾಗಿನ ಮಾಡಿ.'}, 'is_silent': False, 'is_transient': False, 'is_not_critical': False, 'requires_reauth': False, 'allow_user_retry': False, 'debug_info': None, 'query_path': None, 'fbtrace_id': 'FEtFSa/nEel', 'www_request_id': 'AG5Z5T9iq2eNzEV4y96X3sy', 'sentry_block_user_info': {'sentry_block_data': 'AegbYoV57pOYrIvh9yxo_5Ljvhl0m6bCvdGIeHK-lBnv---3J2esDoomd_GAIRH30zCqcaMASO8OCg9vlPmXqJKLFXAdJDAHjpF-px_Cw4tV20UhXw9kD54_R-bCAjKyWXeIPkCd8HjDCa8_S5PJ4PSnnZljCb_Y9CMGl3FNO6Jvf6rFLKtUbCh78WGtR-ZCC-nrCSB-KtIYMuS71J5vN_4CJmgS-N3fF_ToNjMGNajshF3NjRWYkNMqaDaF6JS9pq8Aly8ItPsYYXeQRdwa8wxQ3qYB3JmMGu8p1t3CRTh8JJlAeXrpB_Mv_hQD6OULjkDXt6gcDPsiR-s0sHmMMzdOJudUCEtFMkds5f0fp-RD2XbWTMIt4d-bTnWbvAd7KF4nOwbK1SyCr2B_Yw1EriCD'}}], 'extensions': {'is_final': True}}**

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    ai_sar.start()
  File "D:\CyberEthics\Codiing\Lib\site-packages\ai_sar\ai_sar.py", line 40, in start
    response = ai.prompt(message=CI + '\nUserInput:' + User_input)
  File "D:\CyberEthics\Codiing\Lib\site-packages\meta_ai_api\main.py", line 125, in prompt
    self.access_token = self.get_access_token()
  File "D:\CyberEthics\Codiing\Lib\site-packages\meta_ai_api\main.py", line 92, in get_access_token
    access_token = auth_json["data"]["xab_abra_accept_terms_of_service"][
KeyError: 'data'

**Comment by Strvm** [comment]
@Sm7-git , you seem to have the answer in the error message itself `A server error rate_limit_exceeded occured.`. You are probably using it too much/fast. You could try to use proxies to make that limit higher, nothing I can do more on my end.
