### ISSUE TITLE
Not showing up in my chat history.

### ISSUE THREAD

**Issue by DillonMercz** [Strvm/meta-ai-api#7]
Hello, 

Great work so far, is there any way I can get this to show up in my chat history on meta.ai?

**Comment by sudityashrivastav** [comment]
Yes you can try this api https://rapidapi.com/scoreswift-scoreswift-default/api/meta-llama-3-70b/

**Comment by Strvm** [comment]
> Hello,
> 
> Great work so far, is there any way I can get this to show up in my chat history on meta.ai?

Hi,
yes you can reflect the questions you ask through the library onto meta.ai by authenticating when initializing the lib:

```python
from meta_ai_api import MetaAI
ai = MetaAI(fb_email="your_fb_email", fb_password="your_fb_password")
resp = ai.prompt(message="Generate an image of a tech CEO")
print(resp)
```

**Comment by DillonMercz** [comment]
Awesome! Was using the wrong initialization, Thank you!
